version: 2.1

executors:
  macos:
    macos:
      xcode: 13.4.0

jobs:
  validate_podspec:
    executor: macos
    steps:
      - checkout
      - run:
          name: Validate PodSpec
          command: pod lib lint
  release_sdk:
    executor: macos
    steps:
      - checkout
      - run:
          name: Release SDK to CocoaPods
          command: pod trunk push Judo3DS2_iOS.podspec --allow-warnings

workflows:
  version: 2
  build:
    jobs:
      - validate_podspec
      - release_sdk:
          context: shared-secrets
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only:
                - /^v((\d)+\.){1,2}(\d+)/
